enable-module-update = true
parallel-jobs = 1
patches-version = "latest"
cli-version = "latest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/elohim-etz/morphe-builder/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe
[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[GooglePhotos]
enabled = true
app-name = "GooglePhotos"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
