enable-module-update = true
parallel-jobs = 1
patches-version = "latest"
cli-version = "latest"
cli-source = "MorpheApp/morphe-cli"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/elohim-etz/morphe-builder/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe Patches
[YouTube]
enabled = true
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
version = "20.47.62"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YT-Music]
enabled = true
app-name = "YT-Music"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

# De-Vanced Patches
[Photos]
enabled = true
app-name = "Photos"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "De-Vanced"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Amazon-Music]
enabled = false
app-name = "Amazon-Music"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "De-Vanced"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-music-discover-songs/"
uptodown-dlurl = "https://amazon-mp3.en.uptodown.com/android"

# Hoo-dles Patches
[Amazon-Prime-Video]
enabled = false
app-name = "Amazon-Prime-Video"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
rv-brand = "Hoo-dles"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

# Paresh Patches
[VN-Video-Editor]
enabled = false
app-name = "VN-Video-Editor"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
rv-brand = "Paresh-Patches"
uptodown-dlurl = "https://vn-video-editor.en.uptodown.com/android"

# Crimera Patches
[Twitter]
enabled = true
app-name = "Twitter"
build-mode = "module"
version = "11.81.0-release.0"
include-stock = "split"
patches-source = "crimera/piko"
rv-brand = "Piko"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

# Binarymend Patches
[Pinterest]
enabled = true
app-name = "Pinterest"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
patches-source = "binarymend/morphe-patches"
rv-brand = "binarymend"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/pinterest/"
uptodown-dlurl = "https://pinterest.en.uptodown.com/android"
