enable-module-update = true
parallel-jobs = 1
patches-version = "latest"
cli-version = "latest"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/elohim-etz/morphe-builder/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

# Morphe Patches
[YouTube]
enabled = false
app-name = "YouTube"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music]
enabled = false
app-name = "YouTube-Music"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

# De-Vanced Patches
[Photos]
enabled = false
app-name = "Photos"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Amazon-Music]
enabled = false
app-name = "Amazon-Music"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-music-discover-songs/"
uptodown-dlurl = "https://amazon-mp3.en.uptodown.com/android"

# Hoo-dles Patches
[Amazon-Prime-Video]
enabled = false
app-name = "Amazon-Prime-Video"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/amazon-mobile-llc/amazon-prime-video/"
uptodown-dlurl = "https://amazon-video.en.uptodown.com/android"

# Paresh Patches
[VN-Video-Editor]
enabled = true
app-name = "VN-Video-Editor"
build-mode = "both"
arch = "arm64-v8a"
version = "auto"
patches-source = "Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Paresh-Patches"
uptodown-dlurl = "https://vn-video-editor.en.uptodown.com/android"
